application: flamesgame
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: media/images/favicon.ico
  upload: media/images/favicon.ico

- url: /media/css/(.*)
  static_files: media/css/\1
  upload: media/css/(.*)

- url: .*
  script: main.py

